extranet/protected/modules/enterprise/controllers/EnterpriseController.php
<?php

class EnterpriseController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout='extranet';
    private $pageLimit = 10;

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('index','view','admin','update', 'delete', 'undodelete', 'create', 'refresh','insert','export'),
                'roles'=>array(Role::_ABAMANAGER, Role::_AGENT, Role::_PARTNER),
            ),

            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('index'),
                'roles'=>array(Role::_RESPONSIBLE),
            ),

            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('index', 'refresh','insert','export'),
                'users' => array('@'),
            ),

            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view',array(
            'model'=>$this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model = new Enterprise;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['Enterprise']))
        {
            $model->attributes=$_POST['Enterprise'];
            if($model->save())
                $this->redirect(array('view','id'=>$model->id));
        }

        $this->render('create',array(
            'model'=>$model,
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionInsert() {
        $timeNow = date("Y-m-d H:i:s");

        $allOk = false; $errorMsg = ''; $okMsg = EnterpriseModule::t('Enterprise successfully added.');
        $name = Yii::app()->request->getParam('newEnterpriseName');
        $idCountry = Yii::app()->request->getParam('newEnterpriseCountry');
        $idCourseLang = Yii::app()->request->getParam('newEnterpriseLang');
        $idMainContact = Utils::getSessionVar('id');
        $idType = Yii::app()->request->getParam('newEnterpriseType');
        $idPartnerEnterprise = Yii::app()->params['defaultB2bChannel'];

        $transaction = Yii::app()->dbExtranet->beginTransaction();
        try {
            $mUser = User::model()->findByPK($idMainContact);
            if ( !$mUser ) {
                throw new Exception(Yii::app()->getModule( 'enterprise')->t('Error, something went wrong while trying to find the main contact user.'));
            }

            $mEnterprise = new Enterprise;
            $mEnterprise->name = $name;
            $mEnterprise->idMainContact = $idMainContact;
            $mEnterprise->idUserCreator = $idMainContact;
            $mEnterprise->idLanguage = $idCourseLang;
            $mEnterprise->idCountry = $idCountry;
            $mEnterprise->idType = $idType;
            $mEnterprise->idPartner = Enterprise::idPartnerNextVal($name);
            $mEnterprise->idPartnerEnterprise = $idPartnerEnterprise;
            $mEnterprise->lastupdated = $timeNow;
            $mEnterprise->created = $timeNow;
            $mEnterprise->deleted = $timeNow;
            $mEnterprise->isdeleted = 0;
            $allOk = $mEnterprise->save();
            if (!$allOk) {
                throw new Exception(EnterpriseModule::t('Error, something went wrong while trying to save the enterprise.'));
            }

            $mUserRole = new EnterpriseUserRole;
            $mUserRole->idRole = Role::_RESPONSIBLE;
            $mUserRole->idEnterprise = $mEnterprise->id;
            $mUserRole->idUser = $idMainContact;
            $mUserRole->created = $timeNow;
            $mUserRole->deleted = $timeNow;
            $mUserRole->isdeleted = 0;
            $allOk = $mUserRole->save();
            if (!$allOk) {
                throw new Exception(EnterpriseModule::t('Error, something went wrong while trying to save the user role.'));
            }

            $mUserRole = new EnterpriseUserRole;
            if ( Yii::app()->user->isagent || Yii::app()->user->isabamanager ) $mUserRole->idRole = Role::_AGENT;
            else if ( Yii::app()->user->ispartner ) $mUserRole->idRole = Role::_PARTNER;
            else throw new Exception(EnterpriseModule::t('Error, invalid role.'));
            $mUserRole->idEnterprise = $mEnterprise->id;
            $mUserRole->idUser = $idMainContact;
            $mUserRole->created = $timeNow;
            $mUserRole->deleted = $timeNow;
            $mUserRole->isdeleted = 0;
            $allOk = $mUserRole->save();
            if (!$allOk) {
                throw new Exception(EnterpriseModule::t('Error, something went wrong while trying to save the user role.'));
            }

            $mCountry = Country::model()->findByPk( $idCountry );
            if ( $mCountry ) {
              $idAgent = User::getAgentByCountry( $mCountry->iso );
              if ( $idAgent != $idMainContact ) {
                $mUserRole = new EnterpriseUserRole;
                $mUserRole->idRole = Role::_AGENT;
                $mUserRole->idEnterprise = $mEnterprise->id;
                $mUserRole->idUser = $idAgent;
                $mUserRole->created = $timeNow;
                $mUserRole->deleted = $timeNow;
                $mUserRole->isdeleted = 0;
                $allOk = $mUserRole->save();
                if (!$allOk) {
                  throw new Exception(EnterpriseModule::t('Error, something went wrong while trying to save the user role.').'(2)');
                }
              }
            }

            $mLicenseAvailable = new LicenseAvailable;
            $mLicenseAvailable->idEnterprise = $mEnterprise->id;
            $mLicenseAvailable->idLicenseType = LicenseType::_Trial;
            $mLicenseAvailable->numLicenses = 1;
            $mLicenseAvailable->histLicenses = 1;
            $mLicenseAvailable->lastupdated = date("Y-m-d H:i:s");
            $allOk = $mLicenseAvailable->save();
            if (!$allOk) {
                throw new Exception(PurchaseModule::t('Error, something went wrong while trying to add licenses.'));
            }

            $mEnterprise->updateSelligentData();

            $transaction->commit();
        }
        catch(Exception $e)
        {
            $transaction->rollback();
            $allOk = false;
            $errorMsg = $e->getMessage();
        }

        echo json_encode(array( 'ok' => $allOk, 'errorMsg' => $errorMsg, 'okMsg' => $okMsg ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model=$this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['name']))
        {
            $model->name = $_POST['name'];
            if($model->save()) {
              $model->updateSelligentData();
              $this->redirect(array('update','id'=>$model->id));
            }
        }

        $this->render('update',array(
            'model'=>$model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete() {

      $errorMsg = '';
      $okMsg = '';
      $idEnterprise = Yii::app()->request->getParam('idEnterprise');

      $undoCode = Enterprise::deleteItem( $idEnterprise );
      $allOk = ( $undoCode != false );
      if ( !$allOk ) $errorMsg = Enterprise::$lastErrorMsg;
      else $okMsg = Yii::app()->getModule('enterprise')->t('lbl: The selected enterprise has been removed.').'<a id=\'undoDeleteList_enterprise\' data-undocode=\''.$undoCode.'\' href=\'#\'>'.Yii::t( 'app', 'Undo').'</a>';

      echo json_encode(array( 'ok' => $allOk, 'okMsg' => $okMsg, 'errorMsg' => $errorMsg ));
    }

    /**
     *
     */
    public function actionUndodelete()
    {
      $errorMsg = '';
      $undoCode = Yii::app()->request->getParam( 'undoCode', 0 );

      $allOk = Enterprise::undoDelete( $undoCode );
      if (!$allOk) $errorMsg = Enterprise::$lastErrorMsg;

      echo json_encode(array('ok' => $allOk, 'errorMsg' => $errorMsg));
    }


    /**
     * Lists all models.
     */
    public function actionIndex()
    {
//        if ( Yii::app()->user->isGuest ) $this->redirect( '/user/login/logout' );     // ** No hay sesion.
        if ( Utils::getSessionVar('idRole') == Role::_RESPONSIBLE ) {
            $this->redirect( '/student/main/'.Utils::getSessionVar('idEnterprise') );
        }

        Utils::setSessionVar('idEnterprise', 0);
        Utils::setSessionVar('role', 0);

        /* we get a list of all countries. */

extranet/protected/modules/enterprise/views/enterprise/_enterprises.php
<?php
$fileLogoEnt = Utils::getSessionVar('enterpriseLogo');
?>

<table width="100%">
    <tr>
        <td>
            <span class="sectionTitle"><?php echo Yii::t('app', 'General settings'); ?></span>
        </td>
    </tr>
</table>
<hr class="hrOverTitle">

<?php $form = $this->beginWidget('CActiveForm', array(
  'id' => 'group-form',
  'enableAjaxValidation' => false,
)); ?>
<div class="withBorderBottom">
    <table class="userTable">
        <tr onmouseover="js:showEditImg('enterpriseNameIMG')" onmouseout="js:hideEditImg('enterpriseNameIMG')">
            <td width="40px" class="paddingTop10">
            </td>
            <td width="250px" class="paddingTop10">
                <span class="formLabel"><?php echo EnterpriseModule::t('Company name'); ?></span> <br>
            </td>
            <td class="paddingTop10">

            </td>
        </tr>
        <tr onmouseover="js:showEditImg('enterpriseNameIMG')" onmouseout="js:hideEditImg('enterpriseNameIMG')">
            <td class="paddingBottom10">
                <a href="#" style="cursor: hand"><img
                      src="<?php echo Yii::app()->request->getBaseUrl(true); ?>/images/icons/update.png" width="12px"
                      id="enterpriseNameIMG" style="display: none" class="yeap"
                      onclick="js:transform('enterpriseName','<?php echo $model->name; ?>')"></a>
            </td>
            <td class="paddingBottom10">
                <span class="userTableValue" onclick="js:transform('enterpriseName','<?php echo $model->name; ?>')"
                      id="enterpriseNameINPUT"><?php echo $model->name; ?></span>
            </td>
            <td class="paddingBottom10">
                <button id='enterpriseNameBOT' class='abaButton abaButton-Primary'
                        style="margin-left:40px; display: none"><?php echo EnterpriseModule::t('Save'); ?></button>
            </td>
        </tr>
    </table>
</div>
<?php $this->endWidget(); ?>

<?php $form = $this->beginWidget('CActiveForm', array(
  'id' => 'group-form',
  'enableAjaxValidation' => false,
)); ?>
<?php echo $form->errorSummary($model); ?>
<div class="withBorderBottom">
    <table class="userTable">
        <tr onmouseover="js:showEditImg('mainContactIMG')" onmouseout="js:hideEditImg('mainContactIMG')">
            <td width="40px" class="paddingTop10">
            </td>
            <td width="250px" class="paddingTop10">
                <span class="formLabel"><?php echo EnterpriseModule::t('Main contact'); ?></span> <br>
            </td>
            <td class="paddingTop10">

            </td>
        </tr>
        <tr onmouseover="js:showEditImg('mainContactIMG')" onmouseout="js:hideEditImg('mainContactIMG')">
            <td class="paddingBottom10">
                <a href="#" style="cursor: hand"><img
                      src="<?php echo Yii::app()->request->getBaseUrl(true); ?>/images/icons/update.png" width="12px"
                      id="mainContactIMG" style="display: none" class="yeap"
                      onclick="js:transform('mainContact','<?php echo $model->idMainContact; ?>')"></a>
            </td>
            <td class="paddingBottom10">
                <?php
                echo chtml::dropDownList('mainContact', $model->idMainContact, $possibleMainContacts,
                  array('onchange' => 'js:showAcceptBut(\'mainContact\')'));
                ?>
            </td>
            <td class="paddingBottom10">
                <button id='mainContactBOT' class='abaButton abaButton-Primary'
                        style="margin-left:40px; display: none"><?php echo EnterpriseModule::t('Save'); ?></button>
            </td>
        </tr>
    </table>
</div>
<?php $this->endWidget(); ?>

<div>
    <?php $form = $this->beginWidget('CActiveForm', array(
      'id' => 'logo-form',
      'enableAjaxValidation' => false,
      'htmlOptions' => array('enctype' => 'multipart/form-data'),
    )); ?>
    <table class="userTable">
        <tr onmouseover="js:showEditImg('langIMG')" onmouseout="js:hideEditImg('langIMG')">
            <td width="40px" class="paddingTop10">

            </td>
            <td width="250px" class="paddingTop10">
                <span class="formLabel">
                    <?php
                    if (!empty($fileLogoEnt)) {
                        echo Yii::t('app', 'Select a new logo');
                    } else {
                        echo Yii::t('app', 'Select a logo');
                    }
                    ?>
                </span>
                <br>
            </td>
            <td class="paddingTop10">

            </td>
        </tr>
        <tr onmouseover="js:showEditImg('profileIMG')" onmouseout="js:hideEditImg('profileIMG')">
            <td>
                <a href="#" style="cursor: hand"><img
                      src="<?php echo Yii::app()->request->getBaseUrl(true); ?>/images/icons/update.png" width="12px"
                      id="profileIMG" style="display: none" class="yeap" onclick="js:submitCrop();"></a>
            </td>
            <td>
                <input type="file" name="fileName" id="fileName" size="40" onchange="showAcceptBut('profile')">
            </td>
            <td>
                <button id='profileBOT' class='abaButton abaButton-Primary'
                        style="margin-left:40px; display: none"><?php echo Yii::t('app', 'Save'); ?></button>
            </td>
        </tr>
    </table>
</div>
<?php $this->endWidget(); ?>
<br><br>
<?php

if (!empty($fileLogoEnt)) { ?>
    <div style="align-content: center">
        <p align="center">
            <?php echo Yii::t('app',
              'If you need it, you can crop de image to adjust the logo and keep a good appearance.'); ?>
            <br><br>
            <img id="cropbox"
                 src="<?php echo getenv('AWS_URL_DOMAIN') . $fileLogoEnt; ?>?x=<?php echo rand(); ?>"
                 style="margin-right: 0.5em; display2: none;">
            <br>
            <button id="cropBut" class='abaButton abaButton-Primary'><?php echo Yii::t('app', 'Crop'); ?></button>
        </p>
        <input type="hidden" id="x" name="x"/>
        <input type="hidden" id="y" name="y"/>
        <input type="hidden" id="w" name="w"/>
        <input type="hidden" id="h" name="h"/>
    </div>
<?php } else { ?>
    <img id="cropbox" src="" style="display: none;">
<?php } ?>
<br>

<div style="text-align: center; margin-bottom: 2em">
    <button id="btnBack" type="button" class="abaButton abaButton-Primary"><?php echo Yii::t('app', 'Back'); ?></button>
</div>


<script>
    function showEditImg(editField) {
        $("#" + editField).show()
    }
    function hideEditImg(editField) {
        if ($("#" + editField).hasClass("yeap")) {
            $("#" + editField).hide();
        }
    }
    function transform(id, value) {
        $('#' + id + 'IMG').show();
        $('#' + id + 'IMG').removeClass("yeap");
        $('#' + id + 'INPUT').replaceWith("<input class='form-control addCampStudent' size='35' type='text' id='" + id + "' name='" + id + "' value='" + value + "'> ");
        $('#' + id + 'BOT').show();

    }
    function submitCrop() {
        $('#fileName').click();
    }
    function showAcceptBut(id) {
        $('#' + id + 'IMG').show();
        $('#' + id + 'IMG').removeClass("yeap");
        $('#' + id + 'BOT').show();
    }
    function disableAcceptButAndImg(id) {
        $('#' + id + 'IMG').hide();
        $('#' + id + 'BOT').hide();
    }

    function updateCoords(c) {
        $('#x').val(c.x);
        $('#y').val(c.y);
        $('#w').val(c.w);
        $('#h').val(c.h);
    }
    ;

    function checkCoords() {
        if (parseInt($('#w').val())) return true;
        alert('<?php echo CJavaScript::quote(Yii::t('app','Please select a crop region then press CROP.')); ?>');
        return false;
    }
    ;

    function createCropObject() {
        var jcrop_api;

        jcrop_api = $.Jcrop('#cropbox', {
            onSelect: updateCoords,
            bgColor: 'white',
            bgOpacity: .3,
            aspectRatio: 1
        });

        $('#cropBut').click(function (e) {
            e.preventDefault();

            if (checkCoords()) {
                //ABAShowLoading();
                var parametros = {
                    x: $('#x').val(),
                    y: $('#y').val(),
                    w: $('#w').val(),
                    h: $('#h').val()
                };

                $.ajax({
                    data: parametros,
                    url: "/extranet/crop",
                    context: document.body,
                    type: 'POST',
                    dataType: "json",
                    success: function (data) {
                        if (data.result) {
                            jcrop_api.setImage(data.urlLogo);
                            $('#logoIMG').attr('src', data.urlLogo);
                        }
                        else {
                            alert('<?php echo CJavaScript::quote(Yii::t('app','There was a problem cropping the image.')); ?>');
                        }

                        //ABAStopLoading();
                    },
                    error: function (jqXHR, textStatus, error) {
                        ABAStopLoading();
                        alert(jqXHR + textStatus + error);
                    }
                }).done(function () {
                    //
                });
            }
        });
    }


    $(document).ready(function () {

        <?php
        if($resultMessage<>'') {
        ?>
        setTimeout(function () {
            ABACustomDialog('ERROR', '<?php echo $resultMessage; ?>', false, true);
        }, 1000);
        <?php
        }
        ?>

        if (typeof $('#cropbox') != 'undefined') {
            $('#cropbox').onloadend
            {
                setTimeout(createCropObject, 200);
            }
        }

        $('#btnBack').click(function () {
            var pageURL = '/student/main';
            var parameters = {};

            ABAChangePage(pageURL, parameters);

        });

    });


</script>

extranet/protected/modules/enterprise/views/enterprise/_form.php
<?php
/* @var $this EnterpriseController */
/* @var $model Enterprise */
/* @var $form CActiveForm */
?>
<div class="row-fluid">
    <div class="col-lg-12">
        <div class="form">

        <?php $form=$this->beginWidget('CActiveForm', array(
            'id'=>'enterprise-form',
            // Please note: When you enable ajax validation, make sure the corresponding
            // controller action is handling ajax validation correctly.
            // There is a call to performAjaxValidation() commented in generated controller code.
            // See class documentation of CActiveForm for details on this.
            'enableAjaxValidation'=>false,
        )); ?>

            <p class="note">Fields with <span class="required">*</span> are required.</p>

            <?php echo $form->errorSummary($model); ?>

            <div class="row">
                <?php echo $form->labelEx($model,'name'); ?>
                <?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>128)); ?>
                <?php echo $form->error($model,'name'); ?>
            </div>

            <div class="row">
                <?php echo $form->labelEx($model,'idMainContact'); ?>
                <?php echo $form->textField($model,'idMainContact'); ?>
                <?php echo $form->error($model,'idMainContact'); ?>
            </div>

            <div class="row">
                <?php echo $form->labelEx($model,'lastupdated'); ?>
                <?php echo $form->textField($model,'lastupdated'); ?>
                <?php echo $form->error($model,'lastupdated'); ?>
            </div>

            <div class="row">
                <?php echo $form->labelEx($model,'created'); ?>
                <?php echo $form->textField($model,'created'); ?>
                <?php echo $form->error($model,'created'); ?>
            </div>

            <div class="row">
                <?php echo $form->labelEx($model,'deleted'); ?>
                <?php echo $form->textField($model,'deleted'); ?>
                <?php echo $form->error($model,'deleted'); ?>
            </div>

            <div class="row">
                <?php echo $form->labelEx($model,'isdeleted'); ?>
                <?php echo $form->textField($model,'isdeleted'); ?>
                <?php echo $form->error($model,'isdeleted'); ?>
            </div>

            <div class="row buttons">
                <?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
            </div>

        <?php $this->endWidget(); ?>

        </div><!-- form -->

    </div>
</div>

extranet/protected/modules/enterprise/views/enterprise/_search.php
<?php
/* @var $this EnterpriseController */
/* @var $model Enterprise */
/* @var $form CActiveForm */
?>
<div class="row-fluid">
    <div class="col-lg-12">

        <div class="wide form">

        <?php $form=$this->beginWidget('CActiveForm', array(
            'action'=>Yii::app()->createUrl($this->route),
            'method'=>'get',
        )); ?>

            <div class="row">
                <?php echo $form->label($model,'id'); ?>
                <?php echo $form->textField($model,'id'); ?>
            </div>

            <div class="row">
                <?php echo $form->label($model,'name'); ?>
                <?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>128)); ?>
            </div>

            <div class="row">
                <?php echo $form->label($model,'idMainContact'); ?>
                <?php echo $form->textField($model,'idMainContact'); ?>
            </div>

            <div class="row">
                <?php echo $form->label($model,'lastupdated'); ?>
                <?php echo $form->textField($model,'lastupdated'); ?>
            </div>

            <div class="row">
                <?php echo $form->label($model,'created'); ?>
                <?php echo $form->textField($model,'created'); ?>
            </div>

            <div class="row">
                <?php echo $form->label($model,'deleted'); ?>
                <?php echo $form->textField($model,'deleted'); ?>
            </div>

            <div class="row">
                <?php echo $form->label($model,'isdeleted'); ?>
                <?php echo $form->textField($model,'isdeleted'); ?>
            </div>

            <div class="row buttons">
                <?php echo CHtml::submitButton('Search'); ?>
            </div>

        <?php $this->endWidget(); ?>

        </div><!-- search-form -->
    </div>
</div>

extranet/protected/modules/enterprise/views/enterprise/_view.php
<?php
/* @var $this EnterpriseController */
/* @var $data Enterprise */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('idMainContact')); ?>:</b>
	<?php echo CHtml::encode($data->idMainContact); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('lastupdated')); ?>:</b>
	<?php echo CHtml::encode($data->lastupdated); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('created')); ?>:</b>
	<?php echo CHtml::encode($data->created); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('deleted')); ?>:</b>
	<?php echo CHtml::encode($data->deleted); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('isdeleted')); ?>:</b>
	<?php echo CHtml::encode($data->isdeleted); ?>
	<br />


</div>

extranet/protected/modules/enterprise/views/enterprise/admin.php
<?php
/* @var $this EnterpriseController */
/* @var $model Enterprise */

$selectedIndex = 'Configuracion';

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#enterprise-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>
<?php /*$this->renderPartial('//extranet/menu', array('selectedIndex' => $selectedIndex) ); */ ?>
<div class="row-fluid">
    <div class="col-lg-12 marginTop15">
        <span class="sectionTitle">Manage Enterprises</span>
	    <br>
        <?php echo CHtml::link('Create new enterprise',array('enterprise/create')); ?>
        <br>

        <?php $this->widget('zii.widgets.grid.CGridView', array(
            'id'=>'enterprise-grid',
            'dataProvider'=>$dataProvider,
            'selectableRows' => 1,
            'cssFile' => Yii::app()->request->baseUrl . '/css/gridView.css',
            'pager'=>array('cssFile'=>Yii::app()->request->baseUrl . '/css/pager.css',
                           'prevPageLabel'  => '«',
                           'nextPageLabel'  => '»',
                           'header'=>''),
            //'filter'=>$model,
            'columns'=>array(
                /*'id',*/
                'name',
                array(
                    'name'=>'idMainContact',
                    'value'=>'$data->mainContact->surname.", ".$data->mainContact->name',
                ),
                'lastupdated',
                'created',
                /*'deleted',*/
                /*
                'isdeleted',
                */
                array(
                    'class'=>'CButtonColumn',
                    'htmlOptions' => array('style' => 'width: 70px; text-align: center;'),
                    'header'=>'Options',
                    'buttons' => array(
                        'update'=>array(
                            'imageUrl'=>Yii::app()->request->baseUrl.'/images/icons/update.png',
                        ),
                        'delete'=>array(
                            'imageUrl'=>Yii::app()->request->baseUrl.'/images/icons/delete.png',
                        ),
                        'view'=>array(
                            'imageUrl'=>Yii::app()->request->baseUrl.'/images/icons/view.png',
                        ),
                    ),
                ),
            ),
        )); ?>
    </div>
</div>

extranet/protected/modules/enterprise/views/enterprise/create.php
<?php
/* @var $this EnterpriseController */
/* @var $model Enterprise */

$selectedIndex = 'Configuracion';
?>
<?php /*$this->renderPartial('//extranet/menu', array('selectedIndex' => $selectedIndex) ); */ ?>
<div class="row-fluid">
    <div class="col-lg-12 marginTop15">
         <span class="sectionTitle">Create Enterprise</span>
        <?php $this->renderPartial('_form', array('model'=>$model)); ?>
    </div>
</div>

extranet/protected/modules/enterprise/views/enterprise/update.php
<?php
/* @var $this GroupController */
/* @var $model Group */

$selectedIndex = 'Configuracion';
?>
<?php /* $this->renderPartial('//extranet/menu', array('selectedIndex' => $selectedIndex) ); */ ?>

<div class="row-fluid">
    <div class="col-lg-12 marginTop15">
        <span class="sectionTitle"><?php echo 'Configuración' ?></span>
        <br><br>
        <?php
        $this->widget('zii.widgets.jui.CJuiTabs', array(
            'tabs'=>array(
                'Enterprise'=>$this->renderPartial('_enterprises', array('model'=>$model),true),
            ),
            'themeUrl'=>'/css',
            'theme'=>'',
            'cssFile' => 'tabStyle.css',
            'options'=>array(
                'collapsible'=>true,
                'selected'=>0,
            ),

            'htmlOptions'=>array(
                'style'=>'width:100%;'
            ),
        ));
        ?>
    </div>
</div>

extranet/protected/modules/enterprise/views/enterprise/view.php
<?php
/* @var $this EnterpriseController */
/* @var $model Enterprise */
$selectedIndex = 'Configuracion';
?>
<?php /* $this->renderPartial('//extranet/menu', array('selectedIndex' => $selectedIndex) ); */ ?>
<div class="row-fluid">
    <div class="col-lg-12 marginTop15">
        <span class="sectionTitle">View Enterprise <?php echo $model->name; ?></span>
        <?php $this->widget('zii.widgets.CDetailView', array(
            'data'=>$model,
            'attributes'=>array(
                'id',
                'name',
                array(
                    'name'=>$model->getAttributeLabel('idMainContact'),
                    'value'=>$model->mainContact->surname.", ".$model->mainContact->name,
                ),
                'lastupdated',
                'created',
                'deleted',
                'isdeleted',
            ),
        )); ?>
    </div>
</div>