intranet/protected/controllers/BlognewsletterController.php
<?php

class BlognewsletterController extends AbaController
{

    protected function beforeAction($action)
    {

        if (Yii::app()->user->isGuest) {
            Yii::app()->user->returnUrl = Yii::app()->request->requestUri;
            $this->redirect('/index.php?r=site/login');
        }

        return parent::beforeAction($action);
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex()
    {

        $mPublication = new BlogNewsletterPublication();
        $params = Yii::app()->request->getParam('BlogNewsletterPublication', array('status' => 0));
        $mPublication->attributes = $params;

        $this->render('index', array(
          'mPublish' => $mPublication,
        ));
    }

    public function actionEdit()
    {
        $idPublication = Yii::app()->request->getParam('id', 0);
        $mPublication = BlogNewsletterPublication::model()->findByPk($idPublication);
        if (!$mPublication) {
            $mPublication = new BlogNewsletterPublication();
        }

        $criteria = new CDbCriteria();
        $criteria->addCondition('t.idBlog = :idBlog');
        $criteria->addCondition('t.isdeleted = :isdeleted');
        $criteria->addInCondition('t.idPublication', array(0, $mPublication->id));
        $criteria->params = CMap::mergeArray($criteria->params,
          array(':idBlog' => $mPublication->idBlog, ':isdeleted' => 0));
        $mlPost = BlogPost::model()->findAll($criteria);

        $this->render('edit', array(
          'mPublish' => $mPublication,
          'mlPost' => $mlPost,
        ));

    }

    public function actionUpdate()
    {
        $this->actionEdit();
    }

    public function actionView()
    {
        $this->actionEdit();
    }

    public function actionSave()
    {
        $errorMsg = Yii::t('app', 'Error al tratar de guardar la publicación');
        $allOk = false;

        $buttonType = Yii::app()->request->getParam('buttonType', 'saveButton');
        $status = ($buttonType == 'finishButton') ? BlogNewsletterPublication::_CLOSED : BlogNewsletterPublication::_INPROGRESS;
        $idPublication = Yii::app()->request->getParam('idPublication', 0);
        $idBlog = Yii::app()->request->getParam('idBlog', 0);

        $inputSubject = Yii::app()->request->getParam('inputSubject', '');
        $textareaHeader = Yii::app()->request->getParam('textareaHeader', '');
        $inputTweet = Yii::app()->request->getParam('inputTweet', '');
        $linkTweet = Yii::app()->request->getParam('linkTweet', '');

        $idPost1 = Yii::app()->request->getParam('idPost1', 0);
        $idPost2 = Yii::app()->request->getParam('idPost2', 0);
        $idPost3 = Yii::app()->request->getParam('idPost3', 0);
        $idPost4 = Yii::app()->request->getParam('idPost4', 0);
        $idPost5 = Yii::app()->request->getParam('idPost5', 0);
        $descPost1 = Yii::app()->request->getParam('descPost1');
        $descPost2 = Yii::app()->request->getParam('descPost2');
        $descPost3 = Yii::app()->request->getParam('descPost3');
        $descPost4 = Yii::app()->request->getParam('descPost4');
        $descPost5 = Yii::app()->request->getParam('descPost5');
        $linkPost1 = Yii::app()->request->getParam('linkPost1', Yii::t('app', 'read more') . ' >');
        $linkPost2 = Yii::app()->request->getParam('linkPost2', Yii::t('app', 'read more') . ' >');
        $linkPost3 = Yii::app()->request->getParam('linkPost3', Yii::t('app', 'read more') . ' >');
        $linkPost4 = Yii::app()->request->getParam('linkPost4', Yii::t('app', 'read more') . ' >');
        $linkPost5 = Yii::app()->request->getParam('linkPost5', Yii::t('app', 'read more') . ' >');

        $mPublication = BlogNewsletterPublication::model()->findByPk($idPublication);
        if (!$mPublication) {
            $mPublication = new BlogNewsletterPublication();
        }

        $mPublication->textSubject = trim($inputSubject);
        $mPublication->textHeader = trim($textareaHeader);
        $mPublication->textTweet = trim($inputTweet);
        $mPublication->linkTweet = trim($linkTweet);

        $mPublication->idBlog = $idBlog;
        $mPublication->status = ($mPublication->status == BlogNewsletterPublication::_CLOSED) ? $mPublication->status : $status;
        $mPublication->idPost1 = $idPost1;
        $mPublication->descriptionPost1 = trim($descPost1);
        $mPublication->linkPost1 = trim($linkPost1);
        $mPublication->idPost2 = $idPost2;
        $mPublication->descriptionPost2 = trim($descPost2);
        $mPublication->linkPost2 = trim($linkPost2);
        $mPublication->idPost3 = $idPost3;
        $mPublication->descriptionPost3 = trim($descPost3);
        $mPublication->linkPost3 = trim($linkPost3);
        $mPublication->idPost4 = $idPost4;
        $mPublication->descriptionPost4 = trim($descPost4);
        $mPublication->linkPost4 = trim($linkPost4);
        $mPublication->idPost5 = $idPost5;
        $mPublication->descriptionPost5 = trim($descPost5);
        $mPublication->linkPost5 = trim($linkPost5);

        $allOk = $mPublication->save();

        echo json_encode(array('ok' => $allOk, 'errorMsg' => $errorMsg));
    }

    public function actionPublish()
    {
        $date = Yii::app()->request->getParam('date');

        $allOk = false;
        $errorMsg = Yii::t('app', 'Error al crear la publicación.');

        $transaction = Yii::app()->dbExtranet->beginTransaction();
        try {
            $mlBlog = Blog::model()->findAllByAttributes(array('isdeleted' => 0));
            foreach ($mlBlog as $mBlog) {
                $mPublication = new BlogNewsletterPublication();
                $mPublication->dateToSend = $date;
                $mPublication->idBlog = $mBlog->id;
                $mPublication->status = BlogNewsletterPublication::_NEW;
                $mPublication->lastupdated = date("Y-m-d");
                $allOk = $mPublication->save();
                if (!$allOk) {
                    throw new Exception();
                }
            }

            $allOk = true;
            $transaction->commit();
        } catch (Exception $e) {
            $transaction->rollback();
            $allOk = false;
        }

        echo json_encode(array('ok' => $allOk, 'errorMsg' => $errorMsg));
    }

    public function actionVerifydate()
    {
        $date = Yii::app()->request->getParam('date');

        $mPublication = BlogNewsletterPublication::model()->findAllByAttributes(array('dateToSend' => $date));
        if ($mPublication) {
            $allOk = false;
            $errorMsg = Yii::t('app', 'Publicación ya existente.');
        } else {
            $allOk = true;
            $errorMsg = '';
        }

        echo json_encode(array('ok' => $allOk, 'errorMsg' => $errorMsg));
    }

}

intranet/protected/views/blognewsletter/edit.php
<?php
/* @var $this SiteController */
$this->pageTitle = Yii::app()->name;

$this->breadcrumbs = array(
  'Newsletter' => '/index.php?r=blognewsletter/index',
  'Edit',
);

?>

<!-- https://github.com/stephband/jquery.event.move -->
<script src="/js/jquery.event.move.js"></script>
<!-- https://github.com/stephband/jquery.event.swipe -->
<script src="/js/jquery.event.swipe.js"></script>
<!-- http://bxslider.com/ -->
<script src="/js/bxslider/jquery.bxslider.min.js"></script>
<link href="/js/bxslider/jquery.bxslider.css" rel="stylesheet"/>

<script src="/js/jquery.elastic.source.js"></script>

<!-- FancyBox -->
<link rel="stylesheet" href="/js/fancyapps-fancyBox/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen"/>
<script type="text/javascript" src="/js/fancyapps-fancyBox/jquery.fancybox.pack.js?v=2.1.5"></script>

<script src="/js/aba/core.js"></script>
<link href="/css/sections/blognewsletter/edit.css" rel="stylesheet" media="screen">

<script>
    var arPost = {
        '0': '0',
        <?php $contador = 1; ?>
        <?php foreach( $mlPost as $mPost ) { ?>
        '<?php echo $contador++; ?>': <?php echo $mPost->id ?>,
        <?php } ?>
    };
</script>

<div class="sectionBody">

    <div class="sectionMainBody">

        <div>
            <label for="inputSubject"><?php echo Yii::t('app', 'Subject:'); ?></label>
            <?php $textSubject = ($mPublish->textSubject) ? $mPublish->textSubject : 'Lorem ipsum dolor sit amet'; ?>
            <input class="inputText inputTextHeader" type="text" id="inputSubject" value="<?php echo $textSubject; ?>"
                   maxlength="60">
        </div>

        <div id="divImgCapcalera">
            <div><img src="/images/tmp/capcalera.png"></div>
        </div>

        <div id="divTextareaHeader">
            <h4><?php echo Yii::t('app', 'Hello !'); ?></h4>
            <?php $textHeader = ($mPublish->textHeader) ? $mPublish->textHeader : 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,'; ?>
            <textarea id="textareaHeader" class="inputTextarea" maxlength="1000"><?php echo $textHeader; ?></textarea>
        </div>

        <div class="divTweetBackground">
            <?php $textTweet = ($mPublish->textTweet) ? $mPublish->textTweet : 'Lorem ipsum dolor sit amet'; ?>
            <input class="inputText inputTextTweet" type="text" id="inputTweet" value="<?php echo $textTweet; ?>"
                   maxlength="80">
        </div>

        <div>
            <label for="inputLinkTweet"><?php echo Yii::t('app', 'Link Tweet:'); ?></label>
            <?php $linkTweet = ($mPublish->linkTweet) ? $mPublish->linkTweet : 'Lorem ipsum dolor sit amet:  http://goo.gl/Ov3oZ3 #grammar'; ?>
            <input class="inputText" type="text" id="inputLinkTweet" value="<?php echo $linkTweet; ?>" maxlength="60">
        </div>

        <div class="sliderZone">

            <?php for ($contadorSlider = 1; $contadorSlider < 6; $contadorSlider++) { ?>
                <?php
                $indexIdPost = 'idPost' . $contadorSlider;
                $indexDescPost = 'descriptionPost' . $contadorSlider;
                $indexLinkPost = 'linkPost' . $contadorSlider;
                $$indexIdPost = 0;
                ?>
                <textarea style="display:none;"
                          id="idPost_<?php echo $contadorSlider; ?>"><?php echo $mPublish->$indexIdPost; ?></textarea>
                <textarea style="display:none;"
                          id="descPost_<?php echo $contadorSlider; ?>"><?php echo $mPublish->$indexDescPost; ?></textarea>
                <textarea style="display:none;"
                          id="linkPost_<?php echo $contadorSlider; ?>"><?php echo $mPublish->$indexLinkPost; ?></textarea>
                <div>
                    <ul id="bxslider<?php echo $contadorSlider; ?>" class="bxslider">
                        <li>
                            <p><?php echo Yii::t('app', 'Nothing to send'); ?></p>
                        </li>

                        <?php $contadorPost = 1; ?>
                        <?php foreach ($mlPost as $mPost) { ?>
                            <?php if ($mPublish->$indexIdPost == $mPost->id) {
                                $$indexIdPost = $contadorPost;
                                $descPost = $mPublish->$indexDescPost;
                                $linkPost = $mPublish->$indexLinkPost;
                            } else {
                                $descPost = $mPost->description;
                                $linkPost = Yii::t('app', 'read more') . ' >';
                            }
                            ?>
                            <li>
                                <div class="slide-body" data-group="slide">
                                    <div class="post">
                                        <img src="<?php echo utf8_decode($mPost->urlImage); ?>" class="imgPost">
                                        <h4><?php echo $mPost->title; ?></h4>

                                        <p
                                          id="pDescriptionPost_<?php echo $contadorSlider; ?>_<?php echo $mPost->id; ?>"
                                          class="pDescriptionPost"
                                          data-idSlider="<?php echo $contadorSlider; ?>"><?php echo $descPost; ?></p>

                                        <p>
                                            <input class="inputText inputTextLink"
                                                   data-numSlider="<?php echo $contadorSlider; ?>" type="text"
                                                   id="linkPostInner_<?php echo $contadorSlider; ?>_<?php echo $contadorPost; ?>"
                                                   value="<?php echo $linkPost; ?>" maxlength="15">
                                        </p>
                                    </div>
                                </div>
                            </li>
                            <?php $contadorPost++; ?>
                        <?php } ?>
                    </ul>

                    <div class="divPostEditDescription">
                        <textarea class="inputTextarea inputTextAreaEditPost"
                                  data-idslider="<?php echo $contadorSlider; ?>"
                                  id="descPostInner_<?php echo $contadorSlider; ?>" maxlength="120"></textarea>
                    </div>

                </div>
            <?php } ?>

        </div>

        <div id="divButtonZone">

            <div id="saveButton"><?php echo Yii::t('app', 'Save'); ?></div>
            <div id="finishButton"><?php echo Yii::t('app', 'Finish'); ?></div>

            <div id="backButton"><?php echo Yii::t('app', 'Back'); ?></div>

        </div>

    </div>

</div>

<div id="divHiddenPopup" style="display: none; text-align: center;">
    <table height="100%" width='100%'>
        <tr>
            <td>
                <div style="line-height: 6em;text-align: center;"><img src="/images/loading2.gif"></div>
                <div
                  style="text-align: center; font-weight: bold; font-size: 1.3em; line-height: 3em;"><?php echo Yii::t('app',
                      'Loading'); ?> ...
                </div>
                <div style="text-align: center; font-size: 1em;"><?php echo Yii::t('app',
                      'Please, wait some seconds.'); ?></div>
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
        </tr>
    </table>
</div>

<script>

    $(document).ready(function () {
        resizeSectionBody();

        $(window).resize(function () {
            resizeSectionBody();
        });

        $('#textareaHeader').elastic();
        $('.inputTextAreaEditPost').elastic().keyup(function () {
            var idSlider = $(this).data('idslider');
            var idPost = $('#idPost_' + idSlider).val();
            $('#pDescriptionPost_' + idSlider + '_' + idPost).html($(this).val());
            $('#descPost_' + idSlider).html($(this).val());
        }).blur(function () {
            $('.inputTextAreaEditPost').hide();
        });

        $('.pDescriptionPost').dblclick(function () {
            var idSlider = $(this).data('idslider');
            $('.inputTextAreaEditPost').hide();
            $('#descPostInner_' + idSlider).html($('#descPost_' + idSlider).html());
            $('#descPostInner_' + idSlider).show();
        });

        $('.inputTextLink').change(function () {
            $('#linkPost_' + $(this).data('numslider')).val($(this).val());
        });

        <?php for( $i=1; $i<6; $i++ ) { ?>
        $('#bxslider<?php echo $i; ?>').bxSlider({
            mode: 'fade',
            onSlideAfter: function ($slideElement, oldIndex, newIndex) {
                $('#idPost_<?php echo $i; ?>').html(arPost[newIndex]);

                var descValue = 'pDescriptionPost_<?php echo $i; ?>_' + arPost[newIndex];
                $('#descPost_<?php echo $i; ?>').html($('#' + descValue).html());

                var linkValue = 'linkPostInner_<?php echo $i; ?>_' + newIndex;
                $('#linkPost_<?php echo $i; ?>').html($('#' + linkValue).val());
            },
        }).goToSlide(<?php $indexIdPost = 'idPost'.$i; echo $$indexIdPost; ?>);
        <?php } ?>

        $('#backButton').click(function () {
            var pageURL = '/index.php?r=blognewsletter/index';

            var parameters = {};

            abaCore.changePage(pageURL, parameters);
        });

        $('#saveButton,#finishButton').click(function () {
            var url = '/index.php?r=blognewsletter/save&id=<?php echo $mPublish->id; ?>';

            var parameters = {
                buttonType: $(this).attr('id'),
                idPublication: <?php echo $mPublish->id; ?>,
                idBlog: <?php echo $mPublish->idBlog; ?>,
                idPost1: $('#idPost_1').html(),
                descPost1: $('#descPost_1').html(),
                linkPost1: $('#linkPost_1').html(),
                idPost2: $('#idPost_2').html(),
                descPost2: $('#descPost_2').html(),
                linkPost2: $('#linkPost_2').html(),
                idPost3: $('#idPost_3').html(),
                descPost3: $('#descPost_3').html(),
                linkPost3: $('#linkPost_3').html(),
                idPost4: $('#idPost_4').html(),
                descPost4: $('#descPost_4').html(),
                linkPost4: $('#linkPost_4').html(),
                idPost5: $('#idPost_5').html(),
                descPost5: $('#descPost_5').html(),
                linkPost5: $('#linkPost_5').html(),
                inputSubject: $('#inputSubject').val(),
                textareaHeader: $('#textareaHeader').val(),
                inputTweet: $('#inputTweet').val(),
                linkTweet: $('#inputLinkTweet').val(),
            };

            var successF = function (data) {
                if (data.ok) {
                    var pageURL = '/index.php?r=blognewsletter/index';
                    var parameters = {};

                    abaCore.changePage(pageURL, parameters);
                } else {
                    abaCore.showDialog('<html><body><table width="100%" height="88%"><tr><td width="100%" style="text-align: center;"><img src="/images/redalert2.png" align="bottom">&nbsp; ' + data.errorMsg + '</td></tr></table></body></html>', true, '25%', '25%');
                }
            };

            var errorF = function (data) {
                console.log('error');
            };

            abaCore.launchAjax(url, parameters, successF, errorF);
        });

    });

    function resizeSectionBody() {
        return;
        var header_h = $('#header').outerHeight();
        var menu_h = $('.menu').outerHeight();
        var breadcrumbs_h = $('.breadcrumbs').outerHeight();
        var footer_h = $('#footer').outerHeight();
        var windowBody_h = $(window).outerHeight();
        var contentHeight = $('#content').outerHeight();
        var sectionHeight = $('.sectionBody').outerHeight();

        $('#content').height(windowBody_h - header_h - menu_h - breadcrumbs_h - footer_h - 100);
    }

</script>

intranet/protected/views/blognewsletter/index.php
<?php
/* @var $this SiteController */
$this->pageTitle=Yii::app()->name;

$this->breadcrumbs=array(
  'Newsletter',
);

Yii::app()->clientScript->registerScript('search', "

    function reinstallButtons() {
      $('select[name=\"BlogNewsletterPublication[idBlog]\"]').change( function() {
        return refreshList();
      });
      $('select[name=\"BlogNewsletterPublication[status]\"]').change( function() {
        return refreshList();
      });
      $('select[name=\"BlogNewsletterPublication[dateToSend]\"]').change( function() {
        return refreshList();
      });
    }
    reinstallButtons();
");

?>
<link rel="stylesheet" href="/css/sections/blognewsletter/main.css" type="text/css" media="screen" />
<!-- FancyBox -->
<link rel="stylesheet" href="/js/fancyapps-fancyBox/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
<script type="text/javascript" src="/js/fancyapps-fancyBox/jquery.fancybox.pack.js?v=2.1.5"></script>

<script src="/js/aba/core.js"></script>

  <style>
    #newPublicationButton {
      -webkit-border-radius: 2em;
      -moz-border-radius: 2em;
      border-radius: 2em;

      border: 1px solid #9AAFE5;
      font-weight: bold;
      padding: 0.2em 1em;
      text-decoration: none;

      background: none repeat scroll 0% 0% #0297D1;
      color: #FFF;
      margin: 0.5em;

      cursor: pointer;

      width: auto;
      float: right;
    }
  </style>


<?php $this->widget('application.components.widgets.CGridViewABA', array(
  'id'=>'aba-newsletter-grid',
  'extraInfo'=>array('update', 'view'),
  'cssFile' => Yii::app()->request->baseUrl . '/css/styles.css',
  'pager'=>array('cssFile'=>Yii::app()->request->baseUrl . '/css/pager.css',
    'prevPageLabel'  => '<',
    'nextPageLabel'  => '>',
    'firstPageLabel' => '<<',
    'lastPageLabel'  => '>>',),
  'extraButtons'=>array(

  ), //end ExtraButtons
  'ajaxType' => 'post',
  'afterAjaxUpdate' => 'reinstallButtons',

  'dataProvider'=>$mPublish->searchIndex(),
  'filter'=>$mPublish,
//  'filterSelector'=>'{filter}',
  'columns'=>array
  (

    array(
      'name' => 'idBlog',
      'header' => Yii::t( 'app', 'Blog' ),
      'value' => '$data->blogName( $data->idBlog )',
      'filter' => $mPublish->blogNames(),
    ),

    array(
      'name' => 'status',
      'header' => Yii::t( 'app', 'Status' ),
      'value' => '$data->blogStatus( $data->status )',
      'filter' => $mPublish->blogStatusFilter(),
    ),

    array(
      'name' => 'dateToSend',
      'header' => Yii::t( 'app', 'Fecha' ),
      'value' => '$data->blogFecha( $data->dateToSend )',
      'filter' => $mPublish->blogFechaFilter(),
    ),

    array(
      'header'=>'Options',
      'class'=>'CButtonColumnABA',
    ),

  ),
));

?>
<div style="clear: both;"></div>
<div>
  <div id="newPublicationButton"><?php echo Yii::t('app', 'Nueva publicación'); ?></div>
</div>
<div style="clear: both;"></div>

<script>
  $(document).ready( function() {
    $('#newPublicationButton').click( function() {
      abaCore.showDialog( <?php echo CJavaScript::encode( $this->renderPartial('popup_fechapublicacion', array(), true) ); ?>, true, '250px', '100px' );
    });
  });

  function refreshList() {
    var id='aba-newsletter-grid';
    var inputSelector='#'+id+' .filters input, '+'#'+id+' .filters select';
    var data=$.param($(inputSelector));
    $.fn.yiiGridView.update(id, {data: data});
    return false;
  }

</script>

intranet/protected/views/blognewsletter/popup_fechapublicacion.php
<?php
/* @var $this SiteController */

?>
<div style="border: 1px solid #0297D1; width: 100%; height: 100%; color: #000; padding: 2px;">
  <label for="publicationDatePicker"><?php echo Yii::t('app', 'Seleccionar fecha publicación:'); ?></label>
  <div style="text-align: center;">
  <?php
    $startDate = date("Y-m-d");

    $this->widget('zii.widgets.jui.CJuiDatePicker', array(
      'id' => 'publicationDatePicker',
      'name' => 'startDate',
      'value' => $startDate,
      'language'=> Yii::app()->language,
      'options' => array(
        'dateFormat' => 'yy-mm-dd',
        'changeMonth'=>true,
        'changeYear'=>true,
        'minDate' => $startDate,
      ),
      'htmlOptions' => array(
        'size' => '10',
        'maxlength' => '10',
        'style' => 'readonly'
      ),
    ));

  ?>
  </div>

  <div id="divButtonZone">
    <div id="cancelButton" class="btn"><?php echo Yii::t('app', 'Cancel'); ?></div>
    <div id="okButton" class="btn"><?php echo Yii::t('app', 'Send'); ?></div>
  </div>
</div>
<script>
  $(document).ready( function() {
    $( "#publicationDatePicker" ).datepicker();
    $( "#publicationDatePicker" ).datepicker('option', 'dateFormat', 'yy-mm-dd');
    $( "#publicationDatePicker" ).datepicker('option', 'minDate', '<?php echo $startDate; ?>');
    $( "#publicationDatePicker" ).change( function() {
      var url = '<?php echo Yii::app()->createUrl('blognewsletter/verifyDate');?>';

      var parameters = {
        date: $(this).val()
      };

      var successF = function(data) {
        if ( data.ok ) {

        } else {
          alert(data.errorMsg);
          $('#publicationDatePicker').val('');
        }
      };

      var errorF = function(data) {
        console.log('error');
      };

      abaCore.launchAjax( url, parameters, successF, errorF );
    });

    $('#cancelButton').click( function() {
      $('.fancybox-close').trigger('click');
    });

    $('#okButton').click( function() {
      if ( $('#publicationDatePicker').val() == '' ) return;

      var url = '<?php echo Yii::app()->createUrl('blognewsletter/publish');?>';

      var parameters = {
        date: $('#publicationDatePicker').val()
      };

      var successF = function(data) {
        if ( data.ok ) {
          refreshList();
          $('.fancybox-close').trigger('click');
        } else {
          alert(data.errorMsg);
        }
      };

      var errorF = function(data) {
        console.log('error');
      };

      abaCore.launchAjax( url, parameters, successF, errorF );
    });

  });
</script>